# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170209_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='server_list',
            name='IP',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
